version: "3"
services: 
  db-as:
    image: mariadb
    #container_name: as_maria
    environment:
      - MARIADB_USER=admin
      - MARIADB_PASSWORD=changeme
      - MARIADB_ROOT_PASSWORD=root
      - MARIADB_DATABASE=mydb
    ports:
      - 3399:3306
    volumes:
      - /tmp/mysql:/var/lib/mysql  

  adminer-as:
    image: adminer
    environment:
      - ADMINER_DEFAULT_SERVER=db-as
    ports:
      - 8888:8080

